In [16]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

In [17]:
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [18]:
%ls

kaggle.json  Test.csv

In [19]:
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/MyDrive/Colab Notebooks/input"

In [20]:
%cd "/content/gdrive/MyDrive/Colab Notebooks/input"

/content/gdrive/MyDrive/Colab Notebooks/input

In [21]:
!pwd

/content/gdrive/MyDrive/Colab Notebooks/input

In [22]:
data = pd.read_csv('Test.csv')

In [23]:
data

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,458989,Female,Yes,36,Yes,Engineer,0.0,Low,1.0,Cat_6,B
1,458994,Male,Yes,37,Yes,Healthcare,8.0,Average,4.0,Cat_6,A
2,458996,Female,Yes,69,No,NaN,0.0,Low,1.0,Cat_6,A
3,459000,Male,Yes,59,No,Executive,11.0,High,2.0,Cat_6,B
4,459001,Female,No,19,No,Marketing,NaN,Low,4.0,Cat_6,A
...,...,...,...,...,...,...,...,...,...,...,...
2622,467954,Male,No,29,No,Healthcare,9.0,Low,4.0,Cat_6,B
2623,467958,Female,No,35,Yes,Doctor,1.0,Low,1.0,Cat_6,A
2624,467960,Female,No,53,Yes,Entertainment,NaN,Low,2.0,Cat_6,C
2625,467961,Male,Yes,47,Yes,Executive,1.0,High,5.0,Cat_4,C
2626,467968,Female,No,43,Yes,Healthcare,9.0,Low,3.0,Cat_7,A

In [24]:
A=data[data.Segmentation=="A"]
B=data[data.Segmentation=="B"]
C=data[data.Segmentation=="C"]
D=data[data.Segmentation=="D"]

In [25]:
A.info()
B.info()
C.info()
D.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 846 entries, 1 to 2626
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               846 non-null    int64
 1   Gender           846 non-null    object
 2   Ever_Married     821 non-null    object
 3   Age              846 non-null    int64
 4   Graduated        840 non-null    object
 5   Profession       834 non-null    object
 6   Work_Experience  758 non-null    float64
 7   Spending_Score   846 non-null    object
 8   Family_Size      810 non-null    float64
 9   Var_1            834 non-null    object
 10  Segmentation     846 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 79.3+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 550 entries, 0 to 2622
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               550 non-null    int64
 1   Gender           550 non-null    object
 2   Ever_Married     543 non-null    object
 3   Age              550 non-null    int64
 4   Graduated        544 non-null    object
 5   Profession       542 non-null    object
 6   Work_Experience  496 non-null    float64
 7   Spending_Score   550 non-null    object
 8   Family_Size      527 non-null    float64
 9   Var_1            544 non-null    object
 10  Segmentation     550 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 51.6+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 472 entries, 5 to 2625
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               472 non-null    int64
 1   Gender           472 non-null    object
 2   Ever_Married     466 non-null    object
 3   Age              472 non-null    int64
 4   Graduated        466 non-null    object
 5   Profession       462 non-null    object
 6   Work_Experience  417 non-null    float64
 7   Spending_Score   472 non-null    object
 8   Family_Size      450 non-null    float64
 9   Var_1            466 non-null    object
 10  Segmentation     472 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 44.2+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 759 entries, 6 to 2621
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               759 non-null    int64
 1   Gender           759 non-null    object
 2   Ever_Married     747 non-null    object
 3   Age              759 non-null    int64
 4   Graduated        753 non-null    object
 5   Profession       751 non-null    object
 6   Work_Experience  687 non-null    float64
 7   Spending_Score   759 non-null    object
 8   Family_Size      727 non-null    float64
 9   Var_1            751 non-null    object
 10  Segmentation     759 non-null    object
dtypes: float64(2), int64(2), object(7)
memory usage: 71.2+ KB

In [26]:
from sklearn.preprocessing import LabelEncoder

cat = ["Ever_Married", "Graduated","Gender", "Profession", "Spending_Score", "Var_1", 'Segmentation']
for i in cat:
  le = LabelEncoder()
  labels = le.fit_transform(data[i])
  data.drop(i, axis=1, inplace=True)
  data[i]= labels
data.head()

,ID,Age,Work_Experience,Family_Size,Ever_Married,Graduated,Gender,Profession,Spending_Score,Var_1,Segmentation
0,458989,36,0.0,1.0,1,1,0,2,2,5,1
1,458994,37,8.0,4.0,1,1,1,5,0,5,0
2,458996,69,0.0,1.0,1,0,0,9,2,5,0
3,459000,59,11.0,2.0,1,0,1,4,1,5,1
4,459001,19,NaN,4.0,0,0,0,8,2,5,0

In [27]:
#data.Gender=[1 if x=="Female" else 0 for x in data.Gender]
#data.Gender

In [28]:
#data.Ever_Married=[1 if x=="Yes" else 0 for x in data.Ever_Married]
#data.Ever_Married

In [29]:
#data.Graduated=[1 if x=="Yes" else 0 for x in data.Graduated]
#data.Graduated

In [30]:
#data.Spending_Score=[2 if x=="High" else 0 if x=="Low" else 1 for x in data.Spending_Score]
#data.Spending_Score

In [31]:
eksik_degerler = data.isnull().sum()
eksik_degerler

ID                   0
Age                  0
Work_Experience    269
Family_Size        113
Ever_Married         0
Graduated            0
Gender               0
Profession           0
Spending_Score       0
Var_1                0
Segmentation         0
dtype: int64

# Yeni BÃ¶lÃ¼m

In [32]:
print(data['Profession'].value_counts())

0    802
5    418
3    301
1    242
2    236
7    221
4    176
8    111
6     82
9     38
Name: Profession, dtype: int64

In [34]:
data = data.dropna(axis=0)

In [35]:
data

,ID,Age,Work_Experience,Family_Size,Ever_Married,Graduated,Gender,Profession,Spending_Score,Var_1,Segmentation
0,458989,36,0.0,1.0,1,1,0,2,2,5,1
1,458994,37,8.0,4.0,1,1,1,5,0,5,0
2,458996,69,0.0,1.0,1,0,0,9,2,5,0
3,459000,59,11.0,2.0,1,0,1,4,1,5,1
5,459003,47,0.0,5.0,1,1,1,1,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...
2621,467950,35,1.0,2.0,0,1,0,3,2,5,3
2622,467954,29,9.0,4.0,0,0,1,5,2,5,1
2623,467958,35,1.0,1.0,0,1,0,1,2,5,0
2625,467961,47,1.0,5.0,1,1,1,4,1,3,2
2626,467968,43,9.0,3.0,0,1,0,5,2,6,0

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2267 entries, 0 to 2626
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               2267 non-null   int64
 1   Age              2267 non-null   int64
 2   Work_Experience  2267 non-null   float64
 3   Family_Size      2267 non-null   float64
 4   Ever_Married     2267 non-null   int64
 5   Graduated        2267 non-null   int64
 6   Gender           2267 non-null   int64
 7   Profession       2267 non-null   int64
 8   Spending_Score   2267 non-null   int64
 9   Var_1            2267 non-null   int64
 10  Segmentation     2267 non-null   int64
dtypes: float64(2), int64(9)
memory usage: 212.5 KB

In [37]:
data1=data.drop(["ID","Segmentation"],axis=1)
data1.head(5)

,Age,Work_Experience,Family_Size,Ever_Married,Graduated,Gender,Profession,Spending_Score,Var_1
0,36,0.0,1.0,1,1,0,2,2,5
1,37,8.0,4.0,1,1,1,5,0,5
2,69,0.0,1.0,1,0,0,9,2,5
3,59,11.0,2.0,1,0,1,4,1,5
5,47,0.0,5.0,1,1,1,1,1,3

In [38]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2267 entries, 0 to 2626
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              2267 non-null   int64
 1   Work_Experience  2267 non-null   float64
 2   Family_Size      2267 non-null   float64
 3   Ever_Married     2267 non-null   int64
 4   Graduated        2267 non-null   int64
 5   Gender           2267 non-null   int64
 6   Profession       2267 non-null   int64
 7   Spending_Score   2267 non-null   int64
 8   Var_1            2267 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 177.1 KB

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data1,data.Segmentation,test_size=0.20,random_state=50)

In [40]:
print(x_train)

      Age  Work_Experience  Family_Size  Ever_Married  Graduated  Gender  \
2178   37              1.0          4.0             1          1       1
1478   25              0.0          9.0             0          1       0
1088   32              3.0          7.0             0          0       1
770    36              0.0          1.0             1          1       1
1018   55              0.0          1.0             1          0       0
...   ...              ...          ...           ...        ...     ...
2327   61              1.0          1.0             1          1       0
2505   60              0.0          3.0             1          1       1
2233   35              1.0          3.0             1          1       0
1766   59              1.0          4.0             1          0       1
1996   22              1.0          6.0             0          0       1

      Profession  Spending_Score  Var_1
2178           0               0      5
1478           0               2      5
1088           1               2      3
770            0               2      5
1018           2               2      5
...          ...             ...    ...
2327           0               2      5
2505           0               2      5
2233           2               2      2
1766           4               1      5
1996           5               2      3

[1813 rows x 9 columns]

In [41]:
print(y_test)

2340    3
2127    0
2028    3
212     3
2048    1
       ..
2619    0
2413    0
961     2
470     3
1694    0
Name: Segmentation, Length: 454, dtype: int64

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(x_train,y_train)
tahmin=knn.predict(x_test)

In [43]:
print(tahmin)

[3 0 0 0 0 0 1 0 0 3 3 3 2 3 1 2 0 3 1 1 3 0 1 3 0 0 0 1 3 1 1 0 0 2 0 0 0
 3 3 0 0 1 0 2 3 2 2 3 0 1 0 1 0 0 0 3 3 0 1 0 2 3 0 0 0 2 1 3 0 1 3 1 0 0
 1 0 0 0 0 2 0 0 0 0 3 0 3 0 0 0 0 0 3 1 0 0 2 2 0 1 0 0 1 0 0 0 3 2 0 0 0
 0 3 1 0 3 2 0 0 3 1 0 0 3 0 1 0 3 3 0 1 0 2 0 0 0 0 3 0 0 0 0 0 0 0 0 0 3
 1 3 2 0 3 3 0 1 2 0 0 0 2 1 0 0 3 2 0 1 0 0 3 3 3 1 0 2 1 2 0 0 3 0 3 3 2
 0 2 2 2 0 0 0 0 3 2 3 0 2 2 0 0 3 0 0 2 0 1 0 0 0 3 0 3 0 3 0 0 3 3 3 0 3
 3 0 1 2 0 1 0 2 1 0 3 0 1 3 0 0 1 1 0 1 0 3 3 0 1 1 0 3 1 0 3 3 0 0 0 3 2
 0 1 0 0 3 0 1 0 0 2 0 0 3 3 0 0 3 0 2 1 0 1 3 0 0 3 0 3 0 1 3 1 3 0 0 0 3
 1 3 3 0 3 2 1 2 3 2 0 0 0 0 2 0 3 2 2 3 2 0 0 3 0 0 2 3 1 1 1 0 0 2 0 0 1
 2 3 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 3 0 2 0 2 2 0 0 3 3 3 0 3 3 3 3 0 1 0
 0 3 3 3 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 2 1 1 3 1 3 0 1 0 0 0 0 2 3 0 3 3 3
 0 0 2 3 0 0 0 0 0 3 0 0 0 2 3 1 0 1 3 0 2 0 0 3 0 3 0 0 3 0 0 0 0 0 1 0 3
 3 0 2 3 3 3 3 1 2 2]

In [44]:
print(y_test)

2340    3
2127    0
2028    3
212     3
2048    1
       ..
2619    0
2413    0
961     2
470     3
1694    0
Name: Segmentation, Length: 454, dtype: int64

In [45]:
knn.score(x_test,y_test)

0.32819383259911894